### PR TITLE
Feature average review

### PR DESCRIPTION
**Pull request by zachwreed**
What's in this PR:
- API endpoint for average game rating with game ID
- API endpoint for all games ratings
- Adds avgRating objects to game and games state
- Adds shared JSX function for game and games to use in rendering average rating (may refactor more code like this on review if time permits)

### CODE REVIEW

**Review by mobilemelody — COMMENTED** [review]
Just curious why you didn't just get the averages within the query? Otherwise, seems good to me

**Comment by zachwreed** [comment]
> Just curious why you didn't just get the averages within the query? Otherwise, seems good to me

lol I can't believe I overlooked that. I updated it.

**Review by mobilemelody — APPROVED** [review]
Looks good to me

**Comment by mobilemelody** [comment]
By the way, just saw that you can do partial stars, which might make sense for the average review rating (I just did that for the user's average rating). You just need to add `precision={0.1}` for example to the component properties

https://material-ui.com/components/rating/#half-ratings

**Review by Jedeu — APPROVED** [review]
Looks good to me

**Comment by zachwreed** [comment]
It has half star ratings now. Also fixed the button going from Recommendations to Game page.

**Comment by mobilemelody** [comment]
Looks good, I think this can be merged now

**Pull request merged**
