### PR TITLE
Recommendations

### PR DESCRIPTION
**Pull request by mobilemelody**
### This PR includes:
- Additional insert queries for users and reviews
- API route to get recommendations
- View recommendations (`/games/recommendations`)
- Updates to some of the get games API routes and queries to handle games with no categories

### Future updates:
- Add user info to request
- I essentially copied the Games component into a new Recommendations component, so there's a lot of duplicative code. There's probably an opportunity to refactor this to instead reuse/share the layout template

### CODE REVIEW

**Comment by zachwreed** [comment]
Looks good. Do you want to wait to merge until I have merged the fix for the middleware userID so you can incorporate that?

**Comment by zachwreed** [comment]
Looks good. One suggestion - you may want to add some 
`if(collection.isReceived){}` 
statement to check the collection state.

**Review by Jedeu — APPROVED** [review]
Sweet! Looks good to me

**Comment by mobilemelody** [comment]
> Looks good. Do you want to wait to merge until I have merged the fix for the middleware userID so you can incorporate that?

I'll go ahead and merge this and then do all the user info updates on a separate branch/PR

> Looks good. One suggestion - you may want to add some
> `if(collection.isReceived){}`
> statement to check the collection state.

I assume you mean recommendations and not collections? In which case I do check for `!recommendations.isReceived` (and show a loading spinner if true)

**Comment by zachwreed** [comment]
> I assume you mean recommendations and not collections? In which case I do check for `!recommendations.isReceived` (and show a loading spinner if true)

Whoops, yeah that's what I meant

**Pull request merged**
